### ISSUE TITLE
Other libraries support

### ISSUE THREAD

**Issue by Mylloon** [cloudwithax/pomice#13]
Hello, are there any plans to support other versions of `discord.py` (>=2.0.0a)? `discord.py` is no longer maintained, the three I know of that maintain a fork are [`disnake`](https://github.com/EQUENOS/disnake), [`nextcord`](https://github.com/nextcord/nextcord) and [`pycord`](https://github.com/Pycord-Development/pycord).

Are you planning to support any of them, all of them, or do you prefer to stick with the original version?

**Comment by vveeps** [comment]
as long as the inner voice workings are the same, they should work out of the box as pomice's implementation relies on `discord.VoiceProtocol` and everything discord.py does with it under the hood (`guild.voice_client` etc.)

you're free to test the library with those forks and report back, that'd be appreciated

**Comment by cloudwithax** [comment]
There are plenty of forks of the original discord.py code that are still being actively maintained. Also, no other Lavalink client libraries I know of support those libraries you mentioned due to the fact that they are either incomplete in terms of features or aren't popular enough to justify the demand.

**Comment by cloudwithax** [comment]
Also, Pomice relies heavily on discord.py code and absolutely needs it to function. If we were to support other libraries like the ones you mentioned, that would have to called for a nuclear rewrite of Pomice, which I and my other colleagues do not want to undergo at this time. This issue is now closed.
